version: '2'

run:
  timeout: 5m
  tests: true
  concurrency: 8

linters:
  enable:
    # По умолчанию включенные (важные для корректности)
    - errcheck      # проверка обработки ошибок
    - govet         # статический анализ
    - ineffassign   # неиспользуемые присваивания
    - staticcheck   # мощный статический анализатор (включает gosimple)
    - unused        # неиспользуемый код

    # Дополнительные проверки стиля и качества
    # - revive        # Отключено: слишком много false positives для учебного репозитория
    - gocritic      # различные проверки на баги и стиль
    - misspell      # проверка орфографии
    - goconst       # находит повторяющиеся строки
    - prealloc      # предварительное выделение памяти для слайсов

    # Проверки безопасности и производительности
    - gosec         # проверки безопасности
    - bodyclose     # проверка закрытия HTTP response body
    - sqlclosecheck # проверка закрытия SQL соединений

    # Проверки сложности кода
    - gocyclo       # цикломатическая сложность
    - gocognit      # когнитивная сложность

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - commentFormatting

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  goconst:
    min-len: 2
    min-occurrences: 2

  misspell:
    locale: US

  prealloc:
    simple: true
    range-loops: true
    for-loops: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  # Исключения для некоторых паттернов
  exclude-rules:
    # Не требовать обработку ошибок для fmt.Print* в main
    - path: main\.go
      linters:
        - errcheck
      text: "Error return value of `fmt\\.(Print|Printf|Println)` is not checked"

    # Игнорировать использование переменной в замыкании цикла (часто нормально в тестах)
    - path: _test\.go
      text: "Using the variable on range scope .* in function literal"

    # В тестах можно использовать более длинные функции
    - path: _test\.go
      linters:
        - funlen
        - gocognit
        - gocyclo

    # Игнорировать G404 (weak random) в тестах - детерминированная случайность нужна для воспроизводимости
    - path: _test\.go
      linters:
        - gosec
      text: "G404"