version: 1

settings: # required
  course_name: go

  gitlab_base_url: https://gitlab.manytask.org
  public_repo: go/public-2026-spring
  students_group: go/students-2026-spring

ui:
  task_url_template: https://gitlab.manytask.org/go/students-2026-spring/$USER_NAME/-/tree/main/$TASK_NAME

  # optional, any number of links
  links:
    "Contribute Manytask": https://github.com/manytask

deadlines:
  timezone: Europe/Moscow

  deadlines: hard # hard/interpolate
  # max_submissions: 10  # optional
  # submission_penalty: 0.1  # optional

  schedule:
    - group: Hello World
      start: 2026-02-01 18:00
      steps:
        0.3: 2026-02-22 23:59
      end: 2026-07-10 23:59
      enabled: true
      tasks:
        - task: sum
          score: 100
        - task: tour0
          score: 100
        - task: wordcount
          score: 100
        - task: urlfetch
          score: 100
        - task: fetchall
          score: 100

    - group: Basics
      start: 2026-02-19 18:00
      steps:
        0.3: 2026-03-01 23:59
      end: 2026-07-10 23:59
      enabled: true
      tasks:
        - task: hotelbusiness
          score: 100
        - task: hogwarts
          score: 100
        - task: utf8
          score: 100
        - task: varfmt
          score: 100
        - task: speller
          score: 100
        - task: forth
          score: 100

    - group: Interfaces
      start: 2026-02-26 18:00
      steps:
        0.3: 2026-03-08 23:59
      end: 2026-07-10 23:59
      enabled: true
      tasks:
        - task: otp
          score: 100
        - task: retryupdate
          score: 100
        - task: lrucache
          score: 100
        - task: externalsort
          score: 100
        - task: ciletters
          score: 100
        - task: yamlembed
          score: 100

    - group: Goroutines
      start: 2026-03-05 18:00
      steps:
        0.3: 2026-03-15 23:59
      end: 2026-07-10 23:59
      enabled: true
      tasks:
        - task: tour1
          score: 100
        - task: once
          score: 100
        - task: rwmutex
          score: 100
        - task: waitgroup
          score: 100
        - task: cond
          score: 100
        - task: ratelimit
          score: 100

    - group: "[HW] Gitfame"
      start: 2026-03-05 18:00
      end: 2026-03-20 23:59
      enabled: true
      is_large: true
      tasks:
        - task: gitfame
          score: 0

    - group: Testing
      start: 2026-03-12 18:00
      steps:
        0.3: 2026-03-22 23:59
      end: 2026-07-10 23:59
      enabled: true
      tasks:
        - task: testequal
          score: 100
        - task: fileleak
          score: 100
        - task: tabletest
          score: 100
        - task: tparallel
          score: 200
        - task: iprange
          score: 100

    - group: Concurrency with shared memory
      start: 2026-03-19 18:00
      steps:
        0.3: 2026-03-30 23:59
      end: 2026-07-10 23:59
      enabled: true
      tasks:
        - task: dupcall
          score: 200
        - task: keylock
          score: 200
        - task: batcher
          score: 200
        - task: pubsub
          score: 300

    - group: HTTP
      start: 2026-03-26 18:00
      steps:
        0.3: 2026-04-05 23:59
      end: 2026-07-10 23:59
      enabled: true
      tasks:
        - task: urlshortener
          score: 100
        - task: digitalclock
          score: 100
        - task: middleware
          score: 200
        - task: firewall
          score: 200
        - task: olympics
          score: 200

    - group: Database
      start: 2026-04-02 13:00
      steps:
        0.3: 2026-04-12 23:59
      end: 2026-07-10 23:59
      enabled: true
      tasks:
        - task: dao
          score: 100
        - task: ledger
          score: 200
        - task: shopfront
          score: 100
        - task: rsem
          score: 300

    - group: "[HW] Dist Build"
      start: 2026-04-02 13:00
      end: 2026-05-10 23:59
      enabled: true
      is_large: true
      tasks:
        - task: distbuild
          score: 1

    - group: Generics
      start: 2026-04-13 18:00
      steps:
        0.3: 2026-04-26 23:59
      end: 2026-07-10 23:59
      enabled: true
      tasks:
        - task: genericsum
          score: 100
        - task: treeiter
          score: 100
        - task: consistenthash
          score: 200
        - task: coverme
          score: 300

    - group: Reflect
      start: 2026-04-16 18:00
      steps:
        0.3: 2026-05-03 23:59
      end: 2026-07-10 23:59
      enabled: true
      tasks:
        - task: reversemap
          score: 100
        - task: jsonlist
          score: 100
        - task: jsonrpc
          score: 100
        - task: excelwriter
          score: 200
        - task: structtags
          score: 100

    - group: Low level
      start: 2026-04-23 18:00
      steps:
        0.3: 2026-05-10 23:59
      end: 2026-07-10 23:59
      enabled: true
      tasks:
        - task: illegal
          score: 100
        - task: blowfish
          score: 100
        - task: gzep
          score: 100

    - group: Observability
      start: 2026-05-14 13:00
      end: 2026-07-10 23:59
      enabled: true
      tasks:
        - task: firegod
          score: 200

    - group: Bonus
      start: 2026-04-03 13:00
      end: 2026-07-10 23:59
      enabled: true
      tasks:
        - task: smartsched
          is_bonus: true
          score: 200
          watch:
            - distbuild/pkg/scheduler
        - task: wscat
          is_bonus: true
          score: 200
        - task: gossip
          is_bonus: true
          score: 300
        - task: wasm
          is_bonus: true
          score: 300
        - task: psycher
          is_bonus: true
          score: 200
        - task: testifycheck
          is_bonus: true
          score: 200
