version: 1

settings: # required
  course_name: go

  gitlab_base_url: https://gitlab.manytask.org
  public_repo: go/public-2025-fall
  students_group: go/students-2025-fall

ui:
  task_url_template: https://gitlab.manytask.org/go/public-2025-fall/-/tree/master/$TASK_NAME

  # optional, any number of links
  links:
    "Contribute Manytask": https://github.com/manytask

deadlines:
  timezone: Europe/Moscow

  deadlines: hard # hard/interpolate
  # max_submissions: 10  # optional
  # submission_penalty: 0.1  # optional

  schedule:
    - group: Hello World
      start: 2025-09-11 18:00
      steps:
        0.3: 2025-10-01 00:00
      end: 2025-10-01 00:00
      tasks:
        - task: sum
          score: 100
        - task: tour0
          score: 100
        - task: wordcount
          score: 100
        - task: urlfetch
          score: 100
        - task: fetchall
          score: 100

    - group: Basics
      start: 2025-09-18 18:00 # Чт
      steps:
        0.3: 2025-09-26 23:59 # Чт ровно через неделю
      end: 2025-10-02 17:59 # Чт ровно через 2 недели от start
      tasks:
        - task: hotelbusiness
          score: 100
        - task: hogwarts
          score: 100
        - task: utf8
          score: 100
        - task: varfmt
          score: 100
        - task: speller
          score: 100
        - task: forth
          score: 100

    - group: Interfaces
      start: 2025-09-25 18:00 # Чт (сразу после окончания Basics)
      steps:
        0.3: 2025-10-09 17:59 # Чт
      end: 2025-10-16 17:59 # Чт
      enabled: true
      tasks:
        - task: otp
          score: 100
        - task: retryupdate
          score: 100
        - task: lrucache
          score: 100
        - task: externalsort
          score: 100
        - task: ciletters
          score: 100
        - task: yamlembed
          score: 100

    - group: Goroutines
      start: 2025-10-16 18:00 # Чт
      steps:
        0.3: 2025-10-23 17:59 # Чт
      end: 2025-10-26 23:59 # Вс
      enabled: true
      tasks:
        - task: tour1
          score: 100
        - task: once
          score: 100
        - task: rwmutex
          score: 100
        - task: waitgroup
          score: 100
        - task: cond
          score: 100
        - task: ratelimit
          score: 100

    - group: "[HW] Gitfame"
      start: 2025-10-16 18:00 # Чт
      # Для большого ДЗ steps часто не нужен или срок больше
      end: 2025-11-06 23:59 # Оставляем вашу исходную дату, т.к. это большой проект
      enabled: true
      is_large: true
      tasks:
        - task: gitfame
          score: 0

    - group: Testing
      start: 2025-10-23 18:00 # Чт
      steps:
        0.3: 2025-10-30 17:59 # Чт
      end: 2025-11-06 17:59 # Чт (обратите внимание, сдвинулось на неделю из-за правила)
      enabled: true
      tasks:
        - task: testequal
          score: 100
        - task: fileleak
          score: 100
        - task: tabletest
          score: 100
        - task: tparallel
          score: 200
        - task: iprange
          score: 100

    - group: Concurrency with shared memory
      start: 2025-10-30 18:00 # Чт
      steps:
        0.3: 2025-11-06 17:59 # Чт
      end: 2025-11-13 17:59 # Чт
      enabled: true
      tasks:
        - task: dupcall
          score: 200
        - task: keylock
          score: 200
        - task: batcher
          score: 200
        - task: pubsub
          score: 300

    - group: HTTP
      start: 2025-11-06 18:00 # Чт (исправлено с 2025-03-27)
      steps:
        0.3: 2025-11-13 17:59 # Чт
      end: 2025-11-16 17:59 # Чт (исправлено с 2025-07-10)
      enabled: true
      tasks:
        - task: urlshortener
          score: 100
        - task: digitalclock
          score: 100
        - task: middleware
          score: 200
        - task: firewall
          score: 200
        - task: olympics
          score: 200

    - group: Database
      start: 2025-11-13 18:00 # Чт (исправлено с 2025-04-03)
      steps:
        0.3: 2025-11-23 17:59 # Чт
      end: 2025-11-23 23:59 # Чт (исправлено с 2025-07-10)
      enabled: true
      tasks:
        - task: dao
          score: 100
        - task: ledger
          score: 200
        - task: shopfront
          score: 100
        - task: rsem
          score: 300

    - group: "[HW] Dist Build"
      start: 2025-11-13 18:00 # Чт (исправлено с 2025-04-03)
      end: 2025-12-18 23:59 # Скорректировал, чтобы был после окончания других групп
      enabled: true
      is_large: true
      tasks:
        - task: distbuild
          score: 1

    - group: Generics
      start: 2025-11-20 18:00 # Чт (исправлено с 2025-04-14)
      steps:
        0.3: 2025-11-27 17:59 # Чт
      end: 2025-11-30 17:59 # Чт (исправлено с 2025-07-10)
      enabled: true
      tasks:
        - task: genericsum
          score: 100
        - task: treeiter
          score: 100
        - task: consistenthash
          score: 200
        - task: coverme
          score: 300

    - group: Reflect
      start: 2025-12-04 18:00 # Чт (исправлено с 2025-04-17)
      steps:
        0.3: 2025-12-11 17:59 # Чт
      end: 2025-12-18 17:59 # Чт (исправлено с 2025-07-10)
      enabled: true
      tasks:
        - task: reversemap
          score: 100
        - task: jsonlist
          score: 100
        - task: jsonrpc
          score: 100
        - task: excelwriter
          score: 200
        - task: structtags
          score: 100

    - group: Low level
      start: 2025-12-11 18:00 # Чт (исправлено с 2025-04-24)
      steps:
        0.3: 2025-12-18 17:59 # Чт
      end: 2025-12-25 17:59 # Чт (исправлено с 2025-07-10)
      enabled: true
      tasks:
        - task: illegal
          score: 100
        - task: blowfish
          score: 100
        - task: gzep
          score: 100

    - group: Observability
      start: 2025-12-18 18:00 # Чт (исправлено с 2025-05-15)
      end: 2026-01-08 23:59 # Скорректировал, дал больше времени после Нового Года
      enabled: true
      tasks:
        - task: firegod
          score: 200

    - group: Bonus
      start: 2025-11-20 13:00 # Чт (исправлено с 2025-04-04)
      end: 2026-01-08 23:59 # Скорректировал
      enabled: true
      tasks:
        - task: smartsched
          is_bonus: true
          score: 200
          watch:
            - distbuild/pkg/scheduler
        - task: wscat
          is_bonus: true
          score: 200
        - task: gossip
          is_bonus: true
          score: 300
        - task: wasm
          is_bonus: true
          score: 300
        - task: psycher
          is_bonus: true
          score: 200
        - task: testifycheck
          is_bonus: true
          score: 200
