variables:
  GIT_STRATEGY: clone
  REGISTRY: gitlab.manytask.org:5050/go/public-2025-fall
  REPORT_URL: https://app.manytask.org/api/itmo-go-2025-fall/update_config

stages:
  - build-image
  - deploy-image
  #  - check-repo
  - deploy-manytask
  - build-slides
  - deploy-slides

.docker:
  image: docker:24.0.7
  before_script:
    # register `config.json` to be able to push
    - mkdir -p $HOME/.docker && echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json

rebuild-base-image:
  extends: .docker
  stage: build-image
  script:
    - docker build -f build.docker -t $REGISTRY/build .
    - docker push $REGISTRY/build:latest

deploy:
  extends: .docker
  stage: deploy-image
  only:
    - master
  script:
    - docker pull $REGISTRY/build:latest
    - docker build -f testenv.docker -t $REGISTRY .
    - docker push $REGISTRY:latest

.check:
  extends: .docker
  stage: check-repo
  image: $REGISTRY/build
  script:
    - go mod download
    - golangci-lint run --build-tags private,solution ./...
      #- go test -v -tags private,solution ./...
      #- go test -v -race -tags private,solution ./...
    - sudo -u nobody HOME=/tmp PATH=$PATH git config --global --add safe.directory /builds/slon/shad-go-private
    - sudo -u nobody HOME=/tmp PATH=$PATH /usr/local/go/bin/go test -tags private,solution ./...
    - sudo -u nobody HOME=/tmp PATH=$PATH /usr/local/go/bin/go test -tags private,solution -race ./...

update-config:
  stage: deploy-manytask
  image: curlimages/curl:latest
  only:
    - master
  script:
    - >
      curl -v --fail --silent -X POST \
        -H "Authorization: Bearer $TESTER_TOKEN" \
        -H "Content-type: application/x-yaml" \
        --data-binary "@.manytask.yml" \
        $REPORT_URL

push-to-public:
  stage: deploy-manytask
  image: $REGISTRY
  parallel:
    matrix:
      - REMOTE:
          # - git@gitlab.com:manytask/itmo/go/private.git
          # - git@gitlab.manytask.org:itmo/go/public-2025-fall.git
          - git@gitlab.manytask.org:go/public-2025-fall.git
  only:
    - master
  before_script:
    - eval $(ssh-agent -s)
    - echo "$MANYTASK_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - touch ~/.ssh/config
    - touch ~/.ssh/known_hosts
    - chmod -R 400 ~/.ssh
    - ssh-keyscan gitlab.manytask.org >> ~/.ssh/known_hosts
    - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - testtool list-private-files > /tmp/private_files.txt
    - git filter-repo --force --paths-from-file /tmp/private_files.txt --invert-path
    - git branch -D main || true
    - git checkout -b main
    - git remote rm github || true
    - git remote add -f github $REMOTE
    - git push github master --force

build-slides:
  stage: build-slides
  only:
    - master
  extends: .docker
  script:
    - docker build lectures -t $REGISTRY/lectures
    - docker push $REGISTRY/lectures

deploy-slides:
  stage: deploy-slides
  tags:
    - web # Запускать на конкретном shell runner
  only:
    - master
  script:
    - docker pull $REGISTRY/lectures
    - cd /srv/manytask/go && docker compose up -d
